### ISSUE TITLE
Error in the log

### ISSUE THREAD

**Issue by PalePyth** [yorkeJohn/Tainted-Magic#17]
```
[01:54:00] [Server thread/ERROR]: The mcmod.info file in TaintedMagic-1.1.6.4.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 7 column 5
    at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
    at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
    at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
    at cpw.mods.fml.common.MetadataCollection.from(MetadataCollection.java:55) [MetadataCollection.class:1.7.10-1492.152]
    at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:53) [JarDiscoverer.class:1.7.10-1492.152]
    at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:1.7.10-1492.152]
    at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:1.7.10-1492.152]
    at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:133) [ModDiscoverer.class:1.7.10-1492.152]
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:364) [Loader.class:1.7.10-1492.152]
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:489) [Loader.class:1.7.10-1492.152]
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:1.7.10-1492.152]
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) [FMLCommonHandler.class:1.7.10-1492.152]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_79]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 7 column 5
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:480) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.Streams.parse(Streams.java:44) ~[Streams.class:?]
    ... 14 more
```

Latest.log: https://bpaste.net/show/ba3bc71bb3e9

**Comment by yorkeJohn** [comment]
This issue has already been submitted!!!

**Comment by PalePyth** [comment]
Wait, how to fix it?

**Comment by DSLM** [comment]
See this issue
https://github.com/yorkeJohn/TaintedMagic/issues/15
