### ISSUE TITLE
Crash - NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by TATDK** [yorkeJohn/Tainted-Magic#21]
Version 1.1.6.4

```
java.lang.NullPointerException: Ticking entity
    at taintedmagic.common.lib.handler.TMEventHandler.updateAttackDamage(TMEventHandler.java:112)
    at taintedmagic.common.lib.handler.TMEventHandler.livingTick(TMEventHandler.java:74)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1238_TMEventHandler_livingTick_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityOtherPlayerMP.func_70071_h_(EntityOtherPlayerMP.java:59)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full Crash Report : https://pastebin.com/raw/Z7TiwPXB

**Comment by Sunconure11** [comment]
http://pastebin.com/FwDxVGtX

I'm having a similar issue

**Comment by Eufranio** [comment]
I'm having the same issue. Already fixed?

**Comment by LemADEC** [comment]
Any idea what's causing those crashes?

**Comment by Normal69** [comment]
It seems to be a general error to me. :)

But I had it some long time before when we played on a thaumcraft with lots of mods.
Which pack do you play?

**Comment by LemADEC** [comment]
We've it on our Arcania craft modpack, as found on Technic Launcher. It's related to a wand core or focus from TaintedMagic.

**Comment by yorkeJohn** [comment]
This issue has been happening for many people on many packs. Unless I find anything that directly references an error in my code I am pretty sure it is on TC's side... While TMEventHandler is indeed my code, I think it is TC method that is having issues here.

**Comment by LemADEC** [comment]
The issue is in your own function taintedmagic.common.lib.handler.TMEventHandler.updateAttackDamage, probably a missing null check in your code.

**Comment by LemADEC** [comment]
Actually, I did a quick check on the code: looks like the mod tries to solve damage computation on both server and client side while only the server should do it (client doesn't have all attributes and entities on hand to do the maths properly).

**Comment by yorkeJohn** [comment]
Thank you! I will fix this right away.

**Comment by lilmoefow** [comment]
Which version was this fixed in cause the crash is still happening for players on my server? 

Forge 1.7.10-1614
Thaumcraft-1.7.10-4.2.3.5.jar
TaintedMagic-1.1.6.4.jar

http://pastebin.com/mLauwhka
