### ISSUE TITLE
Last version crash

### ISSUE THREAD

**Issue by linkinkov** [yorkeJohn/Tainted-Magic#47]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 24/07/17 01:47
Description: Exception in server tick loop

java.lang.NoSuchMethodError: taintedmagic.common.items.wand.foci.ItemFocusLumos.spawnParticles(Lnet/minecraft/world/World;DDD)V
	at taintedmagic.common.items.wand.foci.ItemFocusLumos.onFocusRightClick(ItemFocusLumos.java:129)
	at thaumcraft.common.items.wands.ItemWandCasting.func_77659_a(ItemWandCasting.java:627)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:185)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:385)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:523)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:861)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by linkinkov** [comment]
Because spawnParticles client side, on server was crashed

**Comment by linkinkov** [comment]
for fix, i just: 			
if (w.isRemote) {
  spawnParticles(w, p);
}

**Comment by yorkeJohn** [comment]
Fixed.

**Comment by linkinkov** [comment]
I dont see any new commits

**Comment by yorkeJohn** [comment]
I close issues when I fix them not when I commit the code.
